name: demo1
description: 典典的小卖部,淘客版本 qq群667186542 
version: 2.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  url_launcher: ^6.0.6
  flutter_webview_plugin: ^0.4.0
  date_format: ^2.0.2
  shared_preferences: ^2.0.6
  dio: ^4.0.0
  flutter_spinkit: ^5.0.0
  flutter_screenutil: ^5.0.0+2
  flutter_swiper_null_safety: ^1.0.2
  provider: ^5.0.0
  fluro: ^2.0.3
  flutter_easyrefresh: ^2.2.1
  pull_to_refresh: ^2.0.0
  fbutton_nullsafety: ^3.0.1
  fsuper_nullsafety: ^3.0.1
  flustars: ^2.0.1
  common_utils: ^2.0.2
  extended_image: ^4.1.0
  extended_image_library: ^3.1.0
  waterfall_flow: ^3.0.1
  loading_more_list: ^4.0.0
  extended_list: ^3.0.0
  pull_to_refresh_notification: ^2.0.1
  carousel_slider: ^4.0.0
  shimmer: ^2.0.0
  flutter_svg: ^0.22.0
  extended_text_field: ^8.0.0
  extended_text: ^7.0.0
  html: ^0.15.0
  image_picker: ^0.8.0+4
  extended_tabs: ^2.2.0
  after_layout: ^1.1.0
  palette_generator: ^0.3.0
  crypto: ^3.0.1
  encrypt: ^5.0.0
  dd_taoke_sdk: ^1.1.6
  fcontrol_nullsafety: ^2.0.0
  flutter_hooks: ^0.17.0
  hooks_riverpod: ^0.14.0+4
  get_it: ^7.1.3
  http: ^0.13.3
  shelf_proxy: ^1.0.0
  responsive_builder: ^0.4.1
  bubble_tab_indicator: ^0.1.6
  badges: ^2.0.1
  carousel_pro_nullsafety: ^1.0.2
  sp_util: ^2.0.3
  flutter_markdown: ^0.6.2

  # 浏览器监听网络请求
#  flutter_stetho:
#    git:
#      url: git://github.com/irdevp/flutter_stetho.git
#      ref: master

  # windows 组件
#  window_size:
#    git:
#      url: git://github.com/google/flutter-desktop-embedding.git  # 修改窗口标题
#      path: plugins/window_size
#      ref: 7812516a5c1fc8ef379e244106953a2b534432b9
#  filepicker_windows: ^2.0.0  # 文件选择器
#  win32: ^2.1.5   # windows 开放api

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.4
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/nav/
    - assets/icons/
    - assets/svg/
    - assets/json/

